import * as anchor from "@coral-xyz/anchor";
import { Connection, PublicKey, Transaction } from "@solana/web3.js";
import { AnchorProvider, Program } from "@coral-xyz/anchor";
import { SubscriptionContract } from "./types/blocksub_contract";
import idl from "./idl/blocksub_contract.json"; // The IDL generated by Anchor

export class BlockSubSDK {
  private connection: Connection;
  private provider: AnchorProvider;
  private program: Program<SubscriptionContract>;

  constructor(wallet: any, networkUrl: string, programId: string) {
    this.connection = new Connection(networkUrl, "confirmed");
    this.provider = new AnchorProvider(this.connection, wallet, {
      preflightCommitment: "confirmed",
    });

    this.program = new Program(idl as any, programId, this.provider);
  }

  // Subscribe a user to a plan
  async subscribe(
    userPublicKey: PublicKey,
    plan: string,
    amount: number,
    durationInDays: number
  ): Promise<void> {
    const subscriptionAccount = anchor.web3.Keypair.generate();

    const tx = await this.program.methods
      .subscribe(plan, new anchor.BN(amount), new anchor.BN(durationInDays))
      .accounts({
        subscriptionAccount: subscriptionAccount.publicKey,
        user: this.provider.wallet.publicKey,
        systemProgram: anchor.web3.SystemProgram.programId, // Ensure the system program is passed correctly
      })
      .signers([subscriptionAccount])
      .rpc();

    console.log("Subscription transaction:", tx);
  }

  // Check subscription status
  async checkSubscriptionStatus(
    subscriptionAccountPubKey: PublicKey
  ): Promise<boolean> {
    const subscriptionAccount =
      await this.program.account.subscriptionAccount.fetch(
        subscriptionAccountPubKey
      );
    const currentTimestamp = Math.floor(Date.now() / 1000);
    return currentTimestamp < subscriptionAccount.expiryDate;
  }

  // Extend subscription by making an additional payment before expiry
  async extendSubscription(
    subscriptionAccountPubKey: PublicKey,
    additionalDuration: number,
    additionalAmount: number
  ): Promise<void> {
    const subscriptionAccount =
      await this.program.account.subscriptionAccount.fetch(
        subscriptionAccountPubKey
      );

    const currentTimestamp = Math.floor(Date.now() / 1000);
    if (currentTimestamp < subscriptionAccount.expiryDate) {
      const newExpiryDate =
        subscriptionAccount.expiryDate + additionalDuration * 24 * 60 * 60;

      const tx = await this.program.methods
        .subscribe(
          subscriptionAccount.plan,
          new anchor.BN(additionalAmount),
          new anchor.BN(additionalDuration)
        )
        .accounts({
          subscriptionAccount: subscriptionAccountPubKey,
          user: this.provider.wallet.publicKey,
          systemProgram: anchor.web3.SystemProgram.programId,
        })
        .rpc();

      console.log("Subscription extended:", tx);
    } else {
      throw new Error("Subscription has already expired");
    }
  }
}
